# Generated by Django 4.2.7 on 2025-07-19 10:58

import cinema.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.utils.create_custom_path),
        ),
    ]
